### ISSUE TITLE
OnDuty / OffDuty

### ISSUE THREAD

**Issue by Lyllithyss** [SoyUltra/Ultra-Scoreboard#5]
Hi, I realllllyyy love your Scoreboard by the way, very clean and slick !! Good job !

I only have one question.

Is there a way to only count players that are on active duty ? 

What I mean by this is, if 2 Polices are offduty and 1 on duty, it shows that there is still 3 Polices on duty. It counts off duty with on duty.

Is there a way to ONLY counts people that are clocked in ?

I tried to check how to do it on my own, but Im pretty clueless on how to do to this. I usually only works on crafting scripts !

If you cant help me its okay, I just thought I would try here !

Thank you !

**Comment by robertne13** [comment]
it will be fixed on next update thx!

**Comment by LYRYCAL** [comment]
still waiting for this update..

**Comment by Lyllithyss** [comment]
Hi ! I got a friend on this matter, and Dekwer found the problem ! In the server.lua you will find something like those lines

elseif Player.PlayerData.job.name == "taxi" then
                TaxiCount = TaxiCount + 1
                
You will need to add a little something to each jobs you want the scoreboard to count actives duty, like this below : 

elseif Player.PlayerData.job.name == "taxi" **and Player.PlayerData.job.onduty** then
                TaxiCount = TaxiCount + 1
               

Just add ''and Player.PlayerData.job.onduty'' to each one ! I hope this help someone !

**Comment by SoyClau** [comment]
Thanks! @Lyllithyss
